CREATE TABLE Users(
	ID INTEGER NOT NULL,
	Name VARCHAR (255) NOT NULL,
	Registered TIMESTAMP NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE Events(
	UID INTEGER NOT NULL,
	Event SMALLINT NOT NULL,
	Triggered TIMESTAMP NOT NULL,
	PRIMARY KEY (UID, Event, Triggered)
);
PARTITION TABLE Users ON COLUMN ID;
PARTITION TABLE Events ON COLUMN UID;
CREATE PROCEDURE CreateUser AS
    INSERT INTO Users (ID,Name,Registered) VALUES(?,?,CURRENT_TIMESTAMP);
PARTITION PROCEDURE CreateUser ON TABLE Users COLUMN ID;
CREATE PROCEDURE CreateEvent AS
	INSERT INTO Events (UID, Event, Triggered) VALUES (?,?,CURRENT_TIMESTAMP);
PARTITION PROCEDURE CreateEvent ON TABLE Events COLUMN UID;
CREATE PROCEDURE FROM CLASS GetInfo;
PARTITION PROCEDURE GetInfo ON TABLE Events COLUMN UID;
